---
- hosts: avernus
  vars_files:
    - secrets.yml
  become: yes
  gather_facts: true
  roles:
    - { role: ansible-role-server-update }
    - { role: ansible-role-docker }
    - { role: ansible-role-consul }
    - { role: ansible-role-nomad }
